config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'  

  
  
  resources :tasks do
    post '', :to => 'tasks#handle_post_request'
  end
  resources :results
  resources :projects
  
  get "/pages/:page" => "pages#show"
  get '/teste', :to => redirect('/teste.txt')  
  get 'index2', :to => redirect('/pages/index2')
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :results

  # app/models/document.rb
    def initialize(params = {})
      file = params.delete(:file)
      super
      if file
        self.filename = sanitize_filename(file.original_filename)
        self.content_type = file.content_type
        self.file_contents = file.read
      end
    end
    private
      def sanitize_filename(filename)
        # Get only the filename, not the whole path (for IE)
        # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
        return File.basename(filename)
      end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    t = Task.find(params[:id])
		#@results = Result.all
		h = Hash.new  
		r_set =  Result.where(:task_id => t.id).to_a
		#r1_set =  Result.all.to_a
		
		i =0
		j=0
		while r_set.length > 0   do
			
			h[r_set[i].id] = 1
			i=0
			j = 1
			
			while j < r_set.length  do
				
				
				if r_set[i].file_contents==r_set[j].file_contents
					r_set.delete(r_set[j])
					h[r_set[i].id] = h[r_set[i].id] + 1
					j = j - 1	
				end
				
			#	if r_set[i].file_contents==r_set[j].file_contents
					
			#		@strin = @strin + r_set[i].id.to_s + "EH IGUAL A " + r_set[j].id.to_s+ "  "
			#		
				
			#	end
				j= j + 1
			end
			
			if r_set.length > 0 
				r_set.delete(r_set[i])
			end
			
		end

		@results = Result.where(:task_id => t.id)
		
		@h =h    
		
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.times_executed =0;
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def handle_post_request
    
   testy="#{request.body.read}"
  
    r = Result.new(:filename => "teste",:content_type =>"application/octet-stream", :file_contents => testy, :task_id => params[:task_id])
    
    r.save
    
    render text: request.headers['SALVOU']
    
  
 end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:file, :project_id, :times_executed)
    end
    

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
 
  <% if @task.errors.any? %>
  
    <div id="error_explanation">
      
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      
      <ul>
        
      <% @task.errors.full_messages.each do |message| %>
      
        <li><%= message %></li>
        
      <% end %>
      
      </ul>
      
    </div>
    
  <% end %>

  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.collection_select(:project_id, Project.all, :id, :name) %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Content type</th>

      <th>Project</th>
      <th>Times executed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.filename %></td>
        <td><%= task.content_type %></td>

        <td><%= task.project.name %></td>
        <td><%= task.times_executed %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @task.filename %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @task.content_type %>
</p>

<p>
  <strong>File contents:</strong>
  
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project.name %>
</p>

<p>
  <strong>Times executed:</strong>
  <%= @task.times_executed %>
</p>

<br>
<p>
  Results of executions:
</p>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th># FREQUENCY</th>
      
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      
      <% if @h[result.id]   %>
        <tr>
          <td><%= result.id %></td>
          <td><%= @h[result.id] %></td>
          
          <td><%= link_to 'Show', result %></td>
          <td><%= link_to 'Edit', edit_result_path(result) %></td>
          <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<p><%=@strin%></p>
<br>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>