config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'  

  
  
  resources :tasks do
    post '', :to => 'tasks#handle_post_request'
  end
  resources :results
  resources :projects
  
  get "/pages/:page" => "pages#show"
  get '/teste', :to => redirect('/teste.txt')  
  get 'index2', :to => redirect('/pages/index2')
  
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :task

  # app/models/document.rb
    def initialize(params = {})
      file = params.delete(:file)
      super
      if file
        self.filename = sanitize_filename(file.original_filename)
        self.content_type = file.content_type
        self.file_contents = file.read
      end
    end
    private
      def sanitize_filename(filename)
        # Get only the filename, not the whole path (for IE)
        # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
        return File.basename(filename)
      end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
	before_action :set_result, only: [:show, :edit, :update, :destroy]
	protect_from_forgery with: :null_session
			def post_example
				testy="#{request.body.read}"
				r = Result.new(:filename => "teste",:content_type =>"application/octet-stream", :file_contents => testy, :task_id => request.headers['task-id'])
				r.save
				render text:  request.headers['EITA']
			end
		# GET /results
	# GET /results.json
	def index
		@results = Result.all
	end

	# GET /results/1
	# GET /results/1.json
	def show
	end

	# GET /results/new
	def new
		@result = Result.new
	end

	# GET /results/1/edit
	def edit
	end

	# POST /results
	# POST /results.json
	def create
		@result = Result.new(result_params)

		respond_to do |format|
			if @result.save
				format.html { redirect_to @result, notice: 'Result was successfully created.' }
				format.json { render :show, status: :created, location: @result }
			else
				format.html { render :new }
				format.json { render json: @result.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /results/1
	# PATCH/PUT /results/1.json
	def update
		respond_to do |format|
			if @result.update(result_params)
				format.html { redirect_to @result, notice: 'Result was successfully updated.' }
				format.json { render :show, status: :ok, location: @result }
			else
				format.html { render :edit }
				format.json { render json: @result.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /results/1
	# DELETE /results/1.json
	def destroy
		@result.destroy
		respond_to do |format|
			format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_result
		@result = Result.find(params[:id])
	end
		# Never trust parameters from the scary internet, only allow the white list through.
	def result_params
		params.require(:result).permit(:file, :task_id)
	end

	
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>

  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>
      
      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      
      </ul>
      
    </div>
    
  <% end %>

<div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>
  
  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.text_field :task_id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Results</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Content type</th>
      
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.filename %></td>
        <td><%= result.content_type %></td>
        
        <td><%= result.task.id %></td>
        
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @result.filename %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @result.content_type %>
</p>

<p>
  <strong>File contents:</strong>
  <%= @result.file_contents %>
</p>

<p>
  <strong>Project:</strong>
  
  <%= @result.task.project.name %>
  <%= @result.task.project.id %>
  
</p>

<p>
  <strong>Task:</strong>
  <%= @result.task.id %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>